modLoader="javafml"
loaderVersion="*"
issueTrackerURL="https://github.com/Asek3/Oculus/issues"
license="LGPL-3.0-only"

[[mods]]
modId="oculus"
version="${version}"
displayURL = "https://curseforge.com/minecraft/mc-mods/oculus"
displayName="Oculus"
logoFile="oculus-logo.png"
authors="NanoLive, dima_dencep, coderbot, IMS212, Justsnoopy30, FoundationGames"
description='''
Unofficial Fork of "Iris", made to work with FML
'''
provides = ["iris"]

[mods."sodium:options"]
"mixin.features.render.world.sky"=false
"mixin.features.render.entity"=false
"mixin.features.render.gui.font"=false

[[dependencies.oculus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.oculus]]
modId = "embeddium"
mandatory = false
versionRange = "[0.3.1,)"
ordering = "NONE"
side = "CLIENT"